// app-vue-ui/src/views/BlogListView.vue
<template>
  <div class="min-h-screen bg-gray-50">
    <!-- Header with AGoat Blog title and Admin Login link -->
    <header class="bg-white shadow-sm border-b">
      <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-4">
        <div class="flex justify-between items-center">
          <div>
            <h1 class="text-2xl font-bold text-gray-900">AGoat Blog</h1>
            <p class="text-sm text-gray-600">All articles and insights</p>
          </div>
          <router-link 
            v-if="!isAuthenticated" 
            to="/login" 
            class="inline-flex items-center px-4 py-2 border border-transparent text-sm font-medium rounded-md text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500"
          >
            Admin Login
          </router-link>
          <router-link 
            v-else 
            to="/dashboard" 
            class="inline-flex items-center px-4 py-2 border border-transparent text-sm font-medium rounded-md text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500"
          >
            Dashboard
          </router-link>
        </div>
      </div>
    </header>

    <!-- Main content -->
    <main class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
      <!-- Back to list button when viewing single post -->
      <div v-if="showingPost" class="mb-6">
        <button
          @click="backToList"
          class="inline-flex items-center px-4 py-2 border border-gray-300 text-sm font-medium rounded-md text-gray-700 bg-white hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500"
        >
          <svg class="w-4 h-4 mr-2" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 19l-7-7 7-7" />
          </svg>
          Back to All Articles
        </button>
      </div>

      <!-- Single Post View -->
      <div v-if="showingPost && currentPost" class="bg-white rounded-lg shadow-sm p-8">
        <article class="prose prose-lg max-w-none">
          <header class="mb-8">
            <h1 class="text-4xl font-bold text-gray-900 mb-4">{{ currentPost.title }}</h1>
            <div class="flex items-center text-sm text-gray-500 space-x-4">
              <span>By {{ currentPost.author || 'Admin' }}</span>
              <span>•</span>
              <span>{{ formatDate(currentPost.created_at) }}</span>
              <span v-if="currentPost.updated_at && currentPost.updated_at !== currentPost.created_at">
                • Updated {{ formatDate(currentPost.updated_at) }}
              </span>
            </div>
          </header>
          
          <div class="prose prose-lg max-w-none" v-html="getRenderedContent()"></div>
          
          <!-- Login prompt for non-authenticated users -->
          <div v-if="!isAuthenticated && shouldShowLoginPrompt" class="mt-8 p-6 bg-gray-50 rounded-lg border">
            <h3 class="text-lg font-medium text-gray-900 mb-2">Want to read more?</h3>
            <p class="text-gray-600 mb-4">Sign in to access the full article and discover more great content.</p>
            <button
              @click="handleLoginRequested"
              class="inline-flex items-center px-4 py-2 border border-transparent text-sm font-medium rounded-md text-white bg-indigo-600 hover:bg-indigo-700"
            >
              Sign In
            </button>
          </div>
        </article>
      </div>

      <!-- Posts List View -->
      <ViewerMicrofrontend
        v-else
        mode="list"
        :page="currentPage"
        :limit="postsPerPage"
        :height="800"
        @post-clicked="handlePostClick"
        @login-requested="handleLoginRequested"
        @error="handleViewerError"
      />
    </main>
  </div>
</template>

<script setup lang="ts">
import { ref, onMounted, computed, watch } from 'vue'
import { useRouter, useRoute } from 'vue-router'
import { useAuthStore } from '../stores/auth'
import { marked } from 'marked'
import axios from 'axios'
import ViewerMicrofrontend from '../components/ViewerMicrofrontend.vue'

const router = useRouter()
const route = useRoute()
const authStore = useAuthStore()

// State
const currentPage = ref(1)
const postsPerPage = ref(10)
const showingPost = ref(false)
const currentPost = ref<any>(null)
const loading = ref(false)
const error = ref<string | null>(null)

// Computed
const isAuthenticated = computed(() => authStore.isAuthenticated)

const shouldShowLoginPrompt = computed(() => {
  if (!currentPost.value || isAuthenticated.value) return false
  return currentPost.value.content.length > 800
})

// Methods
const formatDate = (dateString: string) => {
  const date = new Date(dateString)
  return date.toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric'
  })
}

const getRenderedContent = () => {
  if (!currentPost.value) return ''
  
  let content = currentPost.value.content
  
  // Truncate content for non-authenticated users
  if (!isAuthenticated.value && content.length > 800) {
    content = content.substring(0, 800) + '...'
  }
  
  // Convert markdown to HTML
  return marked.parse(content) as string
}

const fetchPost = async (postId: string) => {
  loading.value = true
  error.value = null
  
  try {
    const response = await axios.get(`http://localhost:8080/api/posts/${postId}`, {
      withCredentials: true
    })
    
    if (response.data && response.data.data) {
      currentPost.value = response.data.data
      showingPost.value = true
      
      // Update page title
      document.title = `${currentPost.value.title} - AGoat Blog`
    } else {
      error.value = 'Post not found'
    }
  } catch (err: any) {
    error.value = err.response?.data?.message || 'Failed to load post'
    console.error('Error fetching post:', err)
  } finally {
    loading.value = false
  }
}

const handlePostClick = (post: any) => {
  // The PostsList component now handles URL updates
  currentPost.value = post
  showingPost.value = true
  
  // Update page title
  document.title = `${post.title} - AGoat Blog`
}

const backToList = () => {
  showingPost.value = false
  currentPost.value = null
  
  // Remove post-path from URL
  const currentUrl = new URL(window.location.href)
  currentUrl.searchParams.delete('post-path')
  window.history.pushState({}, '', currentUrl.toString())
  
  // Reset page title
  document.title = 'AGoat Blog - Latest Posts and Insights'
}

const handleLoginRequested = () => {
  // Navigate to login page
  router.push('/login')
}

const handleViewerError = (error: string) => {
  console.error('Viewer error:', error)
}

const checkForPostPath = () => {
  const urlParams = new URLSearchParams(window.location.search)
  const postPath = urlParams.get('post-path')
  
  if (postPath) {
    // Extract post ID from the path (format: slug/id)
    const parts = postPath.split('/')
    const postId = parts[parts.length - 1]
    
    if (postId) {
      fetchPost(postId)
    }
  } else {
    showingPost.value = false
    currentPost.value = null
  }
}

// Lifecycle
onMounted(() => {
  // Check for post-path in URL on initial load
  checkForPostPath()
  
  // Set default page title and meta description
  if (!showingPost.value) {
    document.title = 'AGoat Blog - Latest Posts and Insights'
    
    const metaDescription = document.querySelector('meta[name="description"]')
    if (metaDescription) {
      metaDescription.setAttribute('content', 'Discover the latest articles, insights, and stories from AGoat. Read our blog for valuable content and updates.')
    } else {
      const meta = document.createElement('meta')
      meta.name = 'description'
      meta.content = 'Discover the latest articles, insights, and stories from AGoat. Read our blog for valuable content and updates.'
      document.head.appendChild(meta)
    }
  }
  
  // Listen for browser back/forward navigation
  window.addEventListener('popstate', checkForPostPath)
})

// Watch for URL changes (though we're handling this manually now)
watch(() => route.query, () => {
  checkForPostPath()
}, { deep: true })
</script>

<style scoped>
/* Additional styles can be added here if needed */
</style>

// reactjs-app-ui/components/BlogListView.tsx
import React, { useState, useEffect } from 'react'
import { useRouter } from 'next/router'
import { marked } from 'marked'
import axios from 'axios'
import PostsList from './PostsList'
import FederatedComponent from '../src/components/FederatedComponent'
import { buildApiUrl, API_CONFIG } from '../src/config/api'
import { Box, Card, Heading, Text, Button, Flex, Badge, Spinner } from '@radix-ui/themes'
import { ArrowLeftIcon, Pencil1Icon, PersonIcon } from '@radix-ui/react-icons'

interface Post {
  id: string
  title: string
  content: string
  slug: string
  published: boolean
  created_at: string
  updated_at: string
  user_id: string
  author?: string
}

const BlogListView: React.FC = () => {
  const router = useRouter()
  
  // State
  const [currentPage, setCurrentPage] = useState(1)
  const [postsPerPage] = useState(10)
  const [showingPost, setShowingPost] = useState(false)
  const [currentPost, setCurrentPost] = useState<Post | null>(null)
  const [loading, setLoading] = useState(false)
  const [error, setError] = useState<string | null>(null)
  const [isAuthenticated, setIsAuthenticated] = useState(false)
  const [authChecked, setAuthChecked] = useState(false)

  const formatDate = (dateString: string) => {
    const date = new Date(dateString)
    return date.toLocaleDateString('en-US', {
      year: 'numeric',
      month: 'long',
      day: 'numeric'
    })
  }

  const getRenderedContent = () => {
    if (!currentPost) return ''
    
    let content = currentPost.content
    
    // Truncate content for non-authenticated users
    if (!isAuthenticated && content.length > 800) {
      content = content.substring(0, 800) + '...'
    }
    
    // Convert markdown to HTML
    return marked.parse(content) as string
  }

  const fetchPost = async (postId: string) => {
    setLoading(true)
    setError(null)
    
    try {
      const response = await axios.get(buildApiUrl(API_CONFIG.ENDPOINTS.POST(postId)), {
        withCredentials: true
      })
      
      if (response.data && response.data.data) {
        setCurrentPost(response.data.data)
        setShowingPost(true)
        
        // Update page title
        document.title = `${response.data.data.title} - AGoat Blog`
      } else {
        setError('Post not found')
      }
    } catch (err: any) {
      setError(err.response?.data?.message || 'Failed to load post')
      console.error('Error fetching post:', err)
    } finally {
      setLoading(false)
    }
  }

  const handlePostClick = (post: Post) => {
    console.log('BlogListView: Post clicked:', post)
    
    // Set the current post and show single post view
    setCurrentPost(post)
    setShowingPost(true)
    
    // Update URL with post-path parameter
    const postPath = `${post.slug}/${post.id}`
    const currentUrl = new URL(window.location.href)
    currentUrl.searchParams.set('post-path', postPath)
    window.history.pushState({}, '', currentUrl.toString())
    
    // Update page title
    document.title = `${post.title} - AGoat Blog`
  }

  const backToList = () => {
    setShowingPost(false)
    setCurrentPost(null)
    
    // Remove post-path from URL
    const currentUrl = new URL(window.location.href)
    currentUrl.searchParams.delete('post-path')
    window.history.pushState({}, '', currentUrl.toString())
    
    // Reset page title
    document.title = 'AGoat Blog - Latest Posts and Insights'
  }

  const editPost = () => {
    if (currentPost) {
      // Navigate to edit page
      router.push(`/post/${currentPost.id}/edit`)
    }
  }

  const handleLoginRequested = () => {
    // Navigate to login page
    router.push('/login')
  }

  const handleViewerError = (error: Error) => {
    console.error('Viewer error:', error)
    setError(error.message)
  }

  const handlePostsLoaded = (posts: Post[]) => {
    console.log('Posts loaded via federation:', posts.length)
  }

  const checkForPostPath = () => {
    const postPath = router.query['post-path'] as string
    
    if (postPath) {
      // Extract post ID from the path (format: slug/id)
      const parts = postPath.split('/')
      const postId = parts[parts.length - 1]
      
      if (postId) {
        fetchPost(postId)
      }
    } else {
      setShowingPost(false)
      setCurrentPost(null)
    }
  }

  const shouldShowLoginPrompt = () => {
    if (!currentPost || isAuthenticated) return false
    return currentPost.content.length > 800
  }

  useEffect(() => {
    // Check authentication status
    const checkAuth = async () => {
      try {
        const response = await axios.get(buildApiUrl(API_CONFIG.ENDPOINTS.STATUS), {
          withCredentials: true
        })
        setIsAuthenticated(response.data.data?.authenticated || false)
      } catch (err) {
        console.error('Auth check failed:', err)
        setIsAuthenticated(false)
      } finally {
        setAuthChecked(true)
      }
    }

    checkAuth()
  }, []) // Empty dependency array is correct here as we only want to run this once on mount

  useEffect(() => {
    // Check for post-path in URL on initial load
    if (router.isReady) {
      checkForPostPath()
      
      // Check for page parameter in URL
      const pageParam = router.query.page as string
      if (pageParam) {
        setCurrentPage(parseInt(pageParam) || 1)
      }
    }
    
    // Listen for browser back/forward navigation
    const handlePopState = () => checkForPostPath()
    window.addEventListener('popstate', handlePopState)
    
    return () => {
      window.removeEventListener('popstate', handlePopState)
    }
  }, [router.isReady, router.query]) // Dependencies are correct

  // Show loading while checking authentication
  if (!authChecked) {
    return (
      <Flex justify="center" align="center" style={{ minHeight: '100vh' }}>
        <Spinner size="3" />
        <Text ml="3" color="gray">Loading...</Text>
      </Flex>
    )
  }

  return (
    <Box style={{ minHeight: '100vh', backgroundColor: 'var(--gray-1)' }}>
      {/* Header */}
      <Box style={{ backgroundColor: 'white', borderBottom: '1px solid var(--gray-6)' }}>
        <Box style={{ maxWidth: '1200px', margin: '0 auto', padding: '16px 24px' }}>
          <Flex justify="between" align="center">
            <Box>
              <Heading size="6">AGoat Blog</Heading>
              <Text size="2" color="gray">All articles and insights</Text>
            </Box>
            {!isAuthenticated ? (
              <Button onClick={() => router.push('/login')}>
                <PersonIcon />
                Admin Login
              </Button>
            ) : (
              <Button onClick={() => router.push('/dashboard')}>
                Dashboard
              </Button>
            )}
          </Flex>
        </Box>
      </Box>

      {/* Main content */}
      <Box style={{ maxWidth: '1200px', margin: '0 auto', padding: '24px' }}>
        {/* Back to list button when viewing single post */}
        {showingPost && (
          <Box mb="6">
            <Button variant="soft" onClick={backToList}>
              <ArrowLeftIcon />
              Back to All Articles
            </Button>
          </Box>
        )}

        {/* Single Post View */}
        {showingPost && currentPost && (
          <Card size="4" style={{ maxWidth: '800px', margin: '0 auto' }}>
            <Box p="6">
              <Heading size="8" mb="4" style={{ lineHeight: '1.2' }}>
                {currentPost.title}
              </Heading>
              
              <Flex align="center" gap="3" mb="6" style={{ color: 'var(--gray-11)' }}>
                <Text size="2">By {currentPost.author || 'Admin'}</Text>
                <Text size="2">•</Text>
                <Text size="2">{formatDate(currentPost.created_at)}</Text>
                {currentPost.updated_at && currentPost.updated_at !== currentPost.created_at && (
                  <>
                    <Text size="2">•</Text>
                    <Text size="2">Updated {formatDate(currentPost.updated_at)}</Text>
                  </>
                )}
              </Flex>
              
              <Box 
                style={{ 
                  lineHeight: '1.7',
                  fontSize: '16px'
                }}
                dangerouslySetInnerHTML={{ __html: getRenderedContent() }}
              />
              
              {/* Edit button for authenticated users */}
              {isAuthenticated && (
                <Box mt="6" pt="6" style={{ borderTop: '1px solid var(--gray-6)' }}>
                  <Flex justify="between" align="center">
                    <Badge 
                      color={currentPost.published ? 'green' : 'yellow'} 
                      variant="soft"
                      size="2"
                    >
                      {currentPost.published ? 'Published' : 'Draft'}
                    </Badge>
                    <Button onClick={editPost}>
                      <Pencil1Icon />
                      Edit Article
                    </Button>
                  </Flex>
                </Box>
              )}
              
              {/* Login prompt for non-authenticated users */}
              {!isAuthenticated && shouldShowLoginPrompt() && (
                <Card mt="6" style={{ backgroundColor: 'var(--gray-3)' }}>
                  <Box p="4">
                    <Heading size="4" mb="2">Want to read more?</Heading>
                    <Text color="gray" mb="4">Sign in to access the full article and discover more great content.</Text>
                    <Button onClick={handleLoginRequested}>
                      Sign In
                    </Button>
                  </Box>
                </Card>
              )}
            </Box>
          </Card>
        )}

        {/* Posts List View - Using Federated Component with Zero-Knowledge */}
        {!showingPost && (
          <FederatedComponent
            componentName="PostsList"
            remoteName="viewer"
            fallback={PostsList}
            onError={handleViewerError}
            // Props for the PostsList component
            apiUrl={API_CONFIG.BASE_URL}
            showPublishedOnly={true}
            page={currentPage}
            limit={postsPerPage}
            maxContentLength={300}
            isAuthenticated={isAuthenticated}
            onPostClicked={handlePostClick}
            onPostsLoaded={handlePostsLoaded}
          />
        )}
      </Box>
    </Box>
  )
}

export default BlogListView
